package com.example.model;

public enum EventType {
    ORDER_CREATED, PAYMENT_PROCESSING, PAYMENT_SUCCESS,
    PAYMENT_FAILED, SHIPMENT_PROCESSING, SHIPMENT_SUCCESS,
    SHIPMENT_FAILED, NOTIFICATION_SENT
}
